services:

    spring-app:
        build: .
        container_name: coding-dojo-dev
        ports:
            - "8080:8080"   # Spring backend (primary app)
        depends_on:
            - postgres

    wildfly:
        image: quay.io/wildfly/wildfly:latest
        container_name: coding-dojo-wildfly
        ports:
            - "8081:8080"   # Jakarta backend
            - "9990:9990"   # WildFly admin console (infra)
        volumes:
            - ./backend-jakarta/target/backend-jakarta.war:/opt/jboss/wildfly/standalone/deployments/backend-jakarta.war

    postgres:
        image: postgres:16
        container_name: coding-dojo-postgres
        environment:
            POSTGRES_DB: dojo
            POSTGRES_USER: dojo
            POSTGRES_PASSWORD: dojo
        ports:
            - "5432:5432"   # DB (infra)

    adminer:
        image: adminer
        container_name: coding-dojo-adminer
        ports:
            - "9001:8080"   # DB UI (infra)
